### ISSUE TITLE
WinSCPSession is now a required parameter for most cmdlets, examples do not reflect this

### ISSUE THREAD

**Issue by jeffreymcclain** [dotps1/WinSCP#100]
### Issue Description

When you standardized positional bindings (https://github.com/dotps1/WinSCP/commit/d13c883a18d322b5fb06303bca29f261dfeb970b), the WinSCPSession parameter became required for multiple cmdlets, but the examples were not updated to reflect this.

### Example

- https://github.com/dotps1/WinSCP/wiki/Copy-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Get-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Get-WinSCPChildItem
- https://github.com/dotps1/WinSCP/wiki/Get-WinSCPItemChecksum
- https://github.com/dotps1/WinSCP/wiki/Invoke-WinSCPCommand
- https://github.com/dotps1/WinSCP/wiki/Move-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/New-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Receive-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Remove-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Remove-WinSCPSession
- https://github.com/dotps1/WinSCP/wiki/Rename-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Send-WinSCPItem
- https://github.com/dotps1/WinSCP/wiki/Sync-WinSCPPath
- https://github.com/dotps1/WinSCP/wiki/Test-WinSCPPath

### WinSCP-PowerShell Version

5.13.9.1

**Comment by angrymrtom** [comment]
The `-WinSCPSession` parameter has always been mandatory, and is explicitly defined as such in the parameter attirubtes.  It _is_ also reflected in the syntax on the help pages: `-WinSCPSession <WinSCP.Session>`. As there is no square brackets around the parameter, this indicates it is mandatory.  However, none of the examples have that value because I use the `$GlobalParameterBinding` functionality to automatically bind the value from `New-WinSCPSession` to that parameter value on all commands in the WinSCP Module so you don't have to save it as a variable and reuse it.  I am going to leave the examples the way are.  You are correct the examples don't reflect the parameter being mandatory, but syntax definition is correct.

**Comment by dotps1** [comment]
The -WinSCPSession parameter has always been mandatory, and is explicitly defined as such in the parameter attirubtes. It is also reflected in the syntax on the help pages: -WinSCPSession <WinSCP.Session>. As there is no square brackets around the parameter, this indicates it is mandatory. However, none of the examples have that value because I use the $GlobalParameterBinding functionality to automatically bind the value from New-WinSCPSession to that parameter value on all commands in the WinSCP Module so you don't have to save it as a variable and reuse it. I am going to leave the examples the way are. You are correct the examples don't reflect the parameter being mandatory, but syntax definition is correct.
