### ISSUE TITLE
Remove-WinSCPItem lacks a -Force parameter

### ISSUE THREAD

**Issue by tinodo** [dotps1/WinSCP#101]
**Remove-WinSCPItem** lacks a **-Force** parameter, which makes it unusable in automation.

When used in a non-interactive script, you will get an error as such:

A command that prompts the user failed because the host program or the command type does not support user interaction. 
 The host was attempting to request confirmation with the following message: Are you sure you want to perform this 
 action?
 Performing the operation "Remove-WinSCPItem" on target "[somefile]".
 At MyScript:XX char:YY
 + 
 + CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
 + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
 
Can this be implemented?

-Force should suppress the warning and assume "Yes".

**Comment by tinodo** [comment]
Meanwhile, you can of course use **Invoke-WinSCPCommand -WinSCPSession $session -Command "rm [file]"**

**Comment by dotps1** [comment]
Just use the `Confirm` parameter:
`Remove-WinSCPItem -Path '/RemoveMe.txt' -Confirm:$false`

**Comment by jeffreymcclain** [comment]
@dotps1 Did this change get reverted when the build was updated to 5.15.1? https://github.com/dotps1/WinSCP/commit/c6d68244c2edd2b6957503bd738438c795fe180e#diff-d4a64b79b801833ecec48df928548d99

I'm not sure if this was intentional, or if maybe I'm just misreading the version history.

**Comment by dotps1** [comment]
I started to make the change till I realized what I was doing.  But you use the confirm switch to delete without a prompt.

Sent from my iPhone

On May 13, 2019, at 10:23 AM, Jeffrey McClain <notifications@github.com<mailto:notifications@github.com>> wrote:


@dotps1<https://github.com/dotps1> Did this change get reverted when the build was updated to 5.15.1? c6d6824#diff-d4a64b79b801833ecec48df928548d99<https://github.com/dotps1/WinSCP/commit/c6d68244c2edd2b6957503bd738438c795fe180e#diff-d4a64b79b801833ecec48df928548d99>

I'm not sure if this was intentional, or if maybe I'm just misreading the version history.
