### ISSUE TITLE
New-WinSCPSessionOption need parameter name，-username

### ISSUE THREAD

**Issue by chuanjiao10** [dotps1/WinSCP#115]
New-WinSCPSessionOption need parameter name，-username

### Issue Description

when i use -SshPrivateKeyPath ,i need -username,or -usernameforsshPrivateKey
at now:
$a = New-WinSCPSessionOption
$a.username = 'xxx'

### Environment
winscp 5.15.4.0

**Comment by dotps1** [comment]
you need to use a `PSCredential` object, which is both a username and a password.

```
# this will prompt you for a username and password
$credential = Get-Credential
$sessionOptions = New-WinSCPSessionOption -Credential $credential
New-WinSCPSession -SessionOptions $sessionOptions
```

you can view the wiki for more examples.

**Comment by chuanjiao10** [comment]
no,no,no ! Listen carefully to me.
users can use:
1 both ssh username and ssh password.
just like :
$sessionOptions = New-WinSCPSessionOption -Credential $credential
or
2 ssh root@ip -keyfilepath xxx 
# both username and keyfilepath,
such i said:
**when user use -SshPrivateKeyPath ,user need -username,or -usernameforsshPrivateKey**

**Comment by dotps1** [comment]
first of all, choose you words a little bit better, phrases like this:
> no,no,no ! Listen carefully to me.

make me really not want to help you at all.  Remember this is a FREE product, and i gain nothing from supporting it.

second of all, you can create a `PSCredential` object, without assigning it a password.  I use a `PSCredential` object because the powershell gallery doesn't allow you to publish modules that use `UserName` and `Password` parameters.  the `New-WinSCPSessionOption` cmdlet extracts the username from the `PSCredential` object.  the `WinSCP.SessionOptions` class has only 1 `UserName` property, which is set by the username portion of the `PSCredential`.  I can add parameters for anything, but if they can't be passed to the `WinSCP.SessionOptions` object, then it doesn't really matter.  https://winscp.net/eng/docs/library_sessionoptions

```powershell
New-Object -TypeName PSCredential -ArgumentList "User", ([SecureString]::new())
```

**Comment by chuanjiao10** [comment]
>  I use a PSCredential object because the powershell gallery doesn't allow you to publish modules that use UserName and Password parameters. 

Not related to password,only add username parameter !
I don't believe that powershell gallery prohibits adding only username ,because new-pssession has -username parameter too.

```
New-PSSession -UserName  -KeyFilePath
```

**Comment by dotps1** [comment]
`New-PSSession` is not a command in a module you get from the PowerShellGallery, it is part of `Microsoft.PowerShell.Core`.  And, if you look at the link i sent you, the `UserName` property of the `WinSCP.SessionOptions` object is populated by `UserName` property of the `PSCredential` object.  So, just give it a blank `SecureString` as i already suggested.  https://github.com/dotps1/WinSCP/blob/82a55060b154dd47b10ec01f8e25d9a7e7f88817/WinSCP/Public/New-WinSCPSessionOption.ps1#L123

i default the `WinSCP.SessionOptions` object to use a combo of anonymous/blank password. https://github.com/dotps1/WinSCP/blob/82a55060b154dd47b10ec01f8e25d9a7e7f88817/WinSCP/Public/New-WinSCPSessionOption.ps1#L17

**Comment by chuanjiao10** [comment]
Needless to say that nonsense, are you going to never add the "-username" parameter?

**Comment by dotps1** [comment]
No i am not, and if you don't like it, don't use it.

**Comment by chuanjiao10** [comment]
No . You do not want to add a user name （for ssh key file path）.
Anyone who doesn't like it, don't use it.
