### ISSUE TITLE
Can't get tests working

### ISSUE THREAD

**Issue by chrgraefe** [dotps1/WinSCP#125]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

Please provide are more detailed or simpler Description for building and testing the module

Perhaps you should switch to the Windows port of OpenSSH (https://github.com/PowerShell/Win32-OpenSSH). This can be started even without admin permissions.

**Comment by tomohulk** [comment]
so, there is nothing to "build".  All the tests are written to interface with appveyor.  it sets up an FTP server locally, and then runs the tests against that.  So most of configs require the `$APPVEYOR_` environment variables.

And this is just a wrapper around the WinSCP dll, there really isn't functionality added to it.  It would be quite redundant to move to OpenSSH, just use the ssh that ships with PowerShell/win10.

And you don't need to be an admin to use the WinSCP functionality in this module.

**Comment by chrgraefe** [comment]
Okay then another explanation to make my problem more clear.
How do I start pester test? With Invoke-Pester i only get errors.

**Comment by tomohulk** [comment]
Right, I use my `Invoke-AppVeyorBuild.ps1` that installs and configures an FTP server on an appveyor instance, it builds directories and files, and then tests against those.  Which requires the appveyor environment variables that you don't have on your system.  its never going to work.

again, this isn't designed for you to build on your machine, because there is nothing to build.  the only thing that script does is publish to powershellgallery.com if all the tests pass.

**Comment by chrgraefe** [comment]
And also test i cant run locally?
