### ISSUE TITLE
Update to latest (5.19.4) release of WinSCP.NET

### ISSUE THREAD

**Issue by sburbano** [dotps1/WinSCP#137]
v5.19.4 includes some functionalities that I would need to be able to use WinSCP in my PS scripts.

Do you have any (tentative) timeframe for updating the module to the latest WinSCP.Net released version?

Thanks in advance

**Comment by septprip** [comment]
I would suggest to make it possible to use WINSCP_PATH to allow the use of lates WinSCP binaries instead of binaries shipped with this package.

**Comment by tomohulk** [comment]
I am not able to publish to the PowerShell Gallery at this time due to issues with AppVeyor, and TBH not sure how much of that I want to continue to support.  So I move exclusively to GitHub Releases.  You can grab the Module with the latest WinSCP Core here: https://github.com/dotps1/WinSCP/releases/tag/WinSCP-PowerShell-v5.19.6.0
