### ISSUE TITLE
Get-WinSCPChild Item Filtering

### ISSUE THREAD

**Issue by GHRoss** [dotps1/WinSCP#39]
The basic filtering on the Get-WinSCPChildItem filtering is great, but it would be even better if it could accept multiple filters the same way as PowerShell's built in Get-ChildItem cmdlet does.

Thank you.

**Comment by dotps1** [comment]
so, as far as this goes there is two answers
1. it cannot be done because the Filter param in the assembly does not take an array of filter strings http://winscp.net/eng/docs/library_session_enumerateremotefiles
2. we could filter the results after.  My only objection to this is speed.  because right not the filter is being be done on the ftp size, so the files are not even returned if they do not match the filter.  However, I am already doing it that way with the `-Directory` and `-File` parameters.
So, I'm leaning towards option 2.

**Comment by dotps1** [comment]
actually, I'm not seeing where the `-Filter` parameter accepts multiple strings:  https://technet.microsoft.com/en-us/library/hh849800.aspx
