### ISSUE TITLE
Test-WinSCPPath fails on '/' 

### ISSUE THREAD

**Issue by gerane** [dotps1/WinSCP#40]
The following commands will fail. It is testing the homepath as a file and fails, which breaks `Get-WinSCPChilditem`
```powershell
Test-WinSCPPath -WinSCPSession $Session -Path '/'

$WinSCPSession.FileExists('/')
```

These commands work.
```powershell
$ftp.ListDirectory('/')

$WinSCPSession.ListDirectory('/').Files
```

**Comment by dotps1** [comment]
in the next version of the assembly, 5.8, the Get WinChildItem is completely redone, as WinSCP gives me a way to do that within the assembly.  I need to test it, but it will probably work in that version.  Your welcome to download the 5.8_Beta branch and check out some of the new stuff.

**Comment by dotps1** [comment]
I'm not sure where you going with this, because for me testing the home path works.
![image](https://cloud.githubusercontent.com/assets/1016996/17644674/dcdd1e6a-615a-11e6-82d0-4603bdbce4c6.png)
so also using the `Get-WinSCPChildItem` with no parameters works as well:
![image](https://cloud.githubusercontent.com/assets/1016996/17644678/f3ad3fbc-615a-11e6-9d9a-bca889fc9f48.png)

I'm going to close this issue, feel free to reopen it if you feel this is still an issue.  Thanks.
