### ISSUE TITLE
File paths should allow path relative to the working directory

### ISSUE THREAD

**Issue by CW333** [dotps1/WinSCP#81]
_Please fill in the following fields, replacing the values inside the brackets `{{ }}`._

### Issue Description

{{ File paths are treated as absolute instead of relative to the current working directory }}

### Example

{{         $sessionOption.SshPrivateKeyPath = "$topdir\id_rsa.ppk"

$topdir is the working directory, but I still have to include it in the file path or the file id_rsa.ppk is not found.
}}

### Expected Output

{{ Please provide what expect to happen. }}

### Actual Output

{{ Please provide what actually happened. }}

### WinSCP-PowerShell Version

{{ 5.13.3.0 }}\

### Environment

{{ OS: Windows Server 2016 
Name             : Windows PowerShell ISE Host
Version          : 5.1.14393.2430
 }}

**Comment by CW333** [comment]
Hi Thomas,

In my script I have this :

         $sessionOption = New-WinSCPSessionOption  `
                            -Protocol Sftp `
                            -HostName $vurl -PortNumber $port `
                            -SshHostKeyFingerprint $fingerprint
        $sessionOption.UserName = 'gfsnz'
        $sessionOption.SshPrivateKeyPath = "$topdir\id_rsa.ppk"
        $sessionOption.Timeout = (New-TimeSpan -Seconds 20)
 
        $session = New-WinSCPSession -SessionOption $sessionOption 
-SessionLogPath "$topdir\$($site.DataDir)\$dldir\WinSCP.log" 
-ReconnectTime (New-TimeSpan -Seconds 180)
 < ... >
             $xfr = Receive-WinSCPItem -WinSCPSession $session -RemotePath 
'/home/gfsnz/data/*' -LocalPath "$topdir\$($site.DataDir)\$dldir" -Remove

 $topdir is the current working directory, in absolute terms, ie 
c:\xxx\yyy  If I don't include that in the paths for SshPrivateKeyPath, 
SessionLogPath, and LocalPath then the script fails.

Hope this helps 




______________________________________________________

Colin Wall | Senior Engineer | Fuel Systems
DDI +64 6 327 0302 | FAX +64 6 327 6724 | 
EMAIL  colin.wall@gallagher.com | WEB www.gallagher.com

**Comment by dotps1** [comment]
Sorry it has taken so long to respond to this.  I noticed you are not using the `New-WinSCPSessionOption` cmdlet to build your session options.  This may be part of the problem.  Because I run a `Resolve-Path` on the path parameters in that cmdlet.  But when you set them manually like you are in the above example, you are setting them to a relative path, which I am guessing WinSCP itself doesn't support.  See my below example, its with FTPS but I think you'll get the idea:

```
PS C:\Users\dotps1\Documents\GitHub\WinSCP> dir


    Directory: C:\Users\dotps1\Documents\GitHub\WinSCP


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         9/7/2018   2:45 PM                Source
-a----       12/27/2018  12:57 PM           3030 certificate.crt


PS C:\Users\dotps1\Documents\GitHub\WinSCP> Import-Module .\Source\WinSCP
PS C:\Users\dotps1\Documents\GitHub\WinSCP> $print = Get-WinSCPHostKeyFingerprint -SessionOption ( New-WinSCPSessionOption -HostName $env:COMPUTERNAME -Protocol Ftp -FtpSecure Implicit ) -Algorithm MD5
PS C:\Users\dotps1\Documents\GitHub\WinSCP> $pass = ( "dotps1" | ConvertTo-SecureString -Force -AsPlainText )
PS C:\Users\dotps1\Documents\GitHub\WinSCP> $so = New-WinSCPSessionOption -HostName $env:COMPUTERNAME -TlsHostCertificateFingerprint $print -Protocol Ftp -FtpSecure Implicit -TlsClientCertificatePath .\certificate.crt -SecurePrivateKeyPassphrase $pass
PS C:\Users\dotps1\Documents\GitHub\WinSCP> New-WinSCPSession -SessionOption $so

Opened       Timeout HostName
------       ------- --------
True        00:01:00 HostName


PS C:\Users\dotps1\Documents\GitHub\WinSCP> Remove-WinSCPSession
```

as you can see, the certificate is in my current working dir, and I reference it with `.\certificate.crt`.  Please build your `WinSCP.SessionOption` with the `New-WinSCPSessionOption` cmdlet, else you will need to resolves the paths in your code.  I am going to close this unless I hear otherwise from you.

hope this helps!  thanks.

**Comment by CW333** [comment]
Hi Thomas,

Thanks for your response below, and also sorry to be so long replying. I tend to leave a thing alone once I have it working, and only now does a reason arise to re-visit this particular script.

I see now the difference between including a file  path in the NewWinSCPSessionOptions cmdlet and setting it manually. Apparently WinSCP.exe requires absolute file paths which surprised me because in my earlier work using WinSCP.com, relative paths were properly interpreted.

But can I now suggest that for the sake of consistency, you should also do a Resolve-Path on SessionLogPath (in NewWinSCPSession cmdlet) and LocalPath (in Receive-WinSCPItem). There may be similar cases in the other cmdlets, but these are the ones I know about.

Thanks and best regards,
Colin

**Comment by dotps1** [comment]
Sounds like a very reasonable and valid request, I’ll check it out in the morning.  Thanks.

Sent from my iPhone

On Mar 5, 2019, at 7:54 PM, CW333 <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi Thomas,

Thanks for your response below, and also sorry to be so long replying. I tend to leave a thing alone once I have it working, and only now does a reason arise to re-visit this particular script.

I see now the difference between including a file path in the NewWinSCPSessionOptions cmdlet and setting it manually. Apparently WinSCP.exe requires absolute file paths which surprised me because in my earlier work using WinSCP.com<http://WinSCP.com>, relative paths were properly interpreted.

But can I now suggest that for the sake of consistency, you should also do a Resolve-Path on SessionLogPath (in NewWinSCPSession cmdlet) and LocalPath (in Receive-WinSCPItem). There may be similar cases in the other cmdlets, but these are the ones I know about.

Thanks and best regards,
Colin

**Comment by CW333** [comment]
Hi Thomas,

Thanks for your comment.
Of course it isn’t as simple as using Resolve-Path in this context, because it fails if the resolved path doesn’t yet exist. It requires some kind of work around to make it work.

Best regards,
Colin
