### ISSUE TITLE
Remove-Session - sessions still remaining

### ISSUE THREAD

**Issue by bcrownover** [dotps1/WinSCP#86]
### Issue Description
 When starting multiple sessions, only the last one is removed by Remove-WinSCPSession

### Example

PS C:\temp> $s1=New-WinSCPSession -SessionOption $sessionOption
PS C:\temp> $s2=New-WinSCPSession -SessionOption $sessionOption
PS C:\temp> Get-WinSCPSession -WinSCPSession $s1

Opened       Timeout HostName
------       ------- --------
True        00:01:00 servername

PS C:\temp> Get-WinSCPSession -WinSCPSession $s2

Opened       Timeout HostName
------       ------- --------
True        00:01:00 servername

PS C:\temp> Remove-WinSCPSession -WinSCPSession $s1
PS C:\temp> Get-WinSCPSession
PS C:\temp> Remove-WinSCPSession -WinSCPSession $s2
PS C:\temp> Remove-WinSCPSession -WinSCPSession $s1
PS C:\temp> Remove-WinSCPSession -WinSCPSession $s1 -Verbose
PS C:\temp> netstat -n -o|Select-String -Pattern ":22"
  TCP    [Win10 workstation IP]:11782      [Server's IP]:22        ESTABLISHED     12936

I also tried just starting two sessions then running Remove-WinSCPSession without a target but that only works for the first one.

### Expected Output
I expect netstat to show that the connection is gone.

### Actual Output
I see I still have open ssh connections

### WinSCP-PowerShell Version
Version: 5.13.4.0

### Environment
Windows 10 connecting to CentOS running OpenSSH
PS C:\temp> $host
Name             : ConsoleHost
Version          : 5.1.15063.1387

**Comment by dotps1** [comment]
you found an interesting bug for sure.  when the 'new-winscpsession' is created, I actually set global script variables with its value, so you don't have to use the -WinSCPSession parameter all over the place.  so that is why when you use `Remove-WinSCPSession` its only removing the first session (although, it should be actually removing the second 1).  but when you remove it using the variable it should work.  I never considered someone using multiple sessions at once, I may have to rethink the design a little bit.  Let me think on this for a little bit.

**Comment by dotps1** [comment]
The only thing I would be able to do would be to add like a `-ForceAll` switch and then just kill any `winscp.exe` process that exist.

**Comment by bcrownover** [comment]
Sounds completely reasonable to me.

**Comment by tomohulk** [comment]
I implemented this, but it won't make it to the PSGallery until the next build.  you can download the repo and try. it out though if you'd like.
